apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: tenant-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ghcr.io/YOUR_GITHUB_USERNAME/auth-service:v1
        ports:
        - containerPort: 3000
